### ISSUE TITLE
Error returned when called by check_nrpe

### ISSUE THREAD

**Issue by lukebarone** [duffycop/nagios_plugins#1]
OS: Debian Buster  
Nagios Version: 4.4.3  
NRPE Version: 3.2.1

Issue:

When trying to run a check from a central Nagios server, I get an error that the check does not exist. If I run the plugin locally, works perfectly fine.

If this isn't a bug in your plugin, then feel free to close this issue. I'm struggling with this one :(

**Comment by duffycop** [comment]
NRPE needs to be compiled with --enable-command-args.
Thanks for reaching out and the troubleshooting!

Best wishes!
